SET @a = (SELECT MIN(LAT_N) FROM STATION);
SET @b = (SELECT MAX(LAT_N) FROM STATION);
SET @c = (SELECT MIN(LONG_W) FROM STATION);
SET @d = (SELECT MAX(LONG_W) FROM STATION);
SET @distance = SQRT(POWER(@a - @b, 2) + POWER(@c - @d, 2));
SELECT ROUND(@distance, 4);
